export default [
    {
        label: "Annotator", 
        role: 1,
         displayHeaderButtonAnnotatorReviewer: true,  
         displayRecentTasksinAnnotator:true,
         displayMyProgressinAnnotator:true,
         hideHeaderButton:true,
         hideActionscolumn:true,
         
         
    },
    {
        label: "Reviewer",
         role: 2, 
         displayHeaderButtonAnnotatorReviewer: true,  
         displayRecentTasksinAnnotator:true,
         displayMyProgressinAnnotator:true,
         hideHeaderButton:true,
         hideActionscolumn:true,
         displayReviewerReports:true,
    },
    {
        label: "SuperChecker", 
        role: 3, 
        displayHeaderButtonAnnotatorReviewer: true, 
        displayRecentTasksinAnnotator:true,
        displayMyProgressinAnnotator:true,
        hideHeaderButton:true,
        hideActionscolumn:true,
        displayReviewerReports:true,
    },
    {
        label: "WorkspaceManager", 
        role: 4, 
        displayHeaderManager: true, 
        projectSettingsIconButton:true,
        MyProgress:true,
        RecentTasks:true,
        deallocationAnnotatorsAndReviewers:true,
        ArchivedProjectsFilter:true,
        allTaskTab:true,
        Choicetranslationmodel:true,
        filterbyAnnotator:true,
        filterbyReviewer:true,
        isAnnotators:true,
        isReviewer:true,
        displayViewandRemoveButton:true,
        displayReviewerReports:true,
    },
    {
        label: "OrganizationOwner", 
        role: 5,  
        displayHeaderOrganizationOwnerAdmin: true,
        projectSettingsIconButton:true,
        MyProgress:true,
        RecentTasks:true,
        deallocationAnnotatorsAndReviewers:true,
        ArchivedProjectsFilter:true,
        allTaskTab:true,
        hideWorkspaces:true,
        filterbyAnnotator:true,
        filterbyReviewer:true,
        isAnnotators:true,
        isReviewer:true,
        displayViewandRemoveButton:true,
        displayReviewerReports:true,
    },
    {
        label: "Admin", 
        role: 6, 
        displayHeaderOrganizationOwnerAdmin: true,
        projectSettingsIconButton:true,
        MyProgress:true,
        RecentTasks:true,
        deallocationAnnotatorsAndReviewers:true,
        ArchivedProjectsFilter:true,
        allTaskTab:true,
        filterbyAnnotator:true,
        filterbyReviewer:true,
        isAnnotators:true,
        isReviewer:true,
        displayViewandRemoveButton:true,
        displayReviewerReports:true,
        
    }
]