export default {
  CHECK_LOGIN_CREDENTIALS: "CHECK_LOGIN_CREDENTIALS",
  APISTATUS: "APISTATUS",
  GET_PROJECT_DATA:"GET_PROJECT_DATA",
  GET_WORKSPACES_DATA:"GET_WORKSPACES_DATA",
  GET_LOGGED_IN_USER_DATA:"GET_LOGGED_IN_USER_DATA",
  GET_PROJECT_DETAILS:"GET_PROJECT_DETAILS",
  GET_PROJECT_REPORT:"GET_PROJECT_REPORT",
  GET_TASK_LIST:"GET_TASK_LIST",
  GET_WORKSPACE_PROJECT_DATA:"GET_WORKSPACE_PROJECT_DATA",
  GET_WORKSPACE_ANNOTATORS_DATA:"GET_WORKSPACE_ANNOTATORS_DATA",
  GET_WORKSPACE_MANAGERS_DATA:"GET_WORKSPACE_MANAGERS_DATA",
  GET_WORKSPACE_DETAILS:"GET_WORKSPACE_DETAILS",
  GET_SAVE_BUTTON:"GET_SAVE_BUTTON",
  GET_EXPORT_PROJECT_BUTTON:"GET_EXPORT_PROJECT_BUTTON",
  GET_PUBLISH_PROJECT_BUTTON:"GET_PUBLISH_PROJECT_BUTTON",
  GET_PULL_NEW_ITEMS:"GET_PULL_NEW_ITEMS",
  GET_ARCHIVE_PROJECT:"GET_ARCHIVE_PROJECT"
 
};
