name: Build and Release React App for Develop2

on:
  push:
    branches: [develop2]
  workflow_dispatch:
  workflow_call:

env: 
  CI: false
  NODE_OPTIONS: "--max_old_space_size=4096"
  REACT_APP_APIGW_BASE_URL: ${{ secrets.REACT_APP_APIGW_BASE_URL_STAGE }}
  AZURE_CREDS: ${{ secrets.SHOONYA_AZURE_CREDS }}
  AZURE_STORAGEKEY: ${{ secrets.SHOONYA_AZURE_STORAGEKEY_STAGE }}

jobs:
  cicd:
    name: CICD_STAGE
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install Node.js
      uses: actions/setup-node@v2

    - name: Install NPM packages
      run: npm install --legacy-peer-deps
    
    - name: Build project
      run: npm run build

    - name: Azure login
      uses: azure/login@v1
      with:
          creds: ${{ env.AZURE_CREDS }}

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob upload-batch --account-name shoonyastoragestage --account-key ${{ env.AZURE_STORAGEKEY }} -d '$web' -s ./build --overwrite

    - name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:
        inlineScript: |
           az cdn endpoint purge --no-wait --content-paths  "/*" --profile-name stage-react-static --name frontend-stage-shoonya --resource-group shoonya
    
    - name: Azure logout
      run: |
            az logout
      if: always()
