name: Build React App

on:
  push:
    branches:
      - stage
  pull_request:
    branches:
      - stage
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install Node.js
      uses: actions/setup-node@v2

    - name: Install NPM packages
      run: npm ci --legacy-peer-deps
    
    - name: Build project
      run: NODE_OPTIONS="--max_old_space_size=4096" npm run build
    
    - name: Run unit tests
      run: npm test

    - name: Upload production-ready build files
      uses: actions/upload-artifact@v2
      with:
        name: production-files
        path: ./build