name: Deploy React App

on:
  push:
    branches: [develop]
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches: [develop]

env: 
  CI: false
  NODE_OPTIONS: "--max_old_space_size=4096"

jobs:
  build-develop:
    uses: ./.github/workflows/build-develop.yaml
    secrets: inherit
  release-develop:
    name: Deploy React App
    needs: [build-develop]
    runs-on: ubuntu-latest
    
    steps:
    - name: Download artifacts from build pipeline
      uses: actions/download-artifact@v3
      with:
        name: production-files-develop
        path: ./build

    - name: Display structure of downloaded files
      run: ls -R

    - name: Azure login
      uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob upload-batch --account-name shoonyastoragedevelop --account-key ${{ secrets.AZURE_STORAGE_KEY_DEVELOP }} -d '$web' -s ./build

    - name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:
        inlineScript: |
           az cdn endpoint purge --no-wait --content-paths  "/*" --profile-name develop-react-static --name frontend-develop-shoonya --resource-group shoonya
    
    - name: Azure logout
      run: |
            az logout
      if: always()
