name: Deploy React App

on:
  push:
    branches: [prod]
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches: [prod]

env: 
  CI: false
  NODE_OPTIONS: "--max_old_space_size=4096"

jobs:
  build-prod:
    uses: ./.github/workflows/build.yaml
    secrets: inherit
  release-prod:
    name: Deploy React App
    needs: [build-prod]
    runs-on: ubuntu-latest
    
    steps:
    - name: Download artifacts from build pipeline
      uses: actions/download-artifact@v3
      with:
        name: production-files-prod
        path: ./build

    - name: Display structure of downloaded files
      run: ls -R

    - name: Azure login
      uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob upload-batch --account-name shoonyastorageprod --account-key ${{ secrets.AZURE_STORAGE_KEY_PROD }} -d '$web' -s ./build

    - name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:
        inlineScript: |
           az cdn endpoint purge --no-wait --content-paths  "/*" --profile-name prod-react-static --name frontend-prod-shoonya --resource-group shoonya
    
    - name: Azure logout
      run: |
            az logout
      if: always()