name: Deploy React App

on:
  push: [stage]
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches: [stage]

env: 
  CI: false
  NODE_OPTIONS: "--max_old_space_size=4096"

jobs:
  build-stage:
    uses: ./.github/workflows/build.yaml
    secrets: inherit
  release-stage:
    name: Deploy React App
    needs: [build-stage]
    runs-on: ubuntu-latest
    
    steps:
    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: build.yml
        workflow_conclusion: success
    
    - name: Azure login
      uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Upload to Azure blob storage
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
            az storage blob upload-batch --account-name shoonyastorage -d '$web' -s ./production-files
    
    - name: Azure logout
      run: |
            az logout